### ISSUE TITLE
PIP install 위치 찾기

### ISSUE THREAD

**Issue by merrym4n** [GSSecurity/OSS#1]
merryman:sample merryman$ **pip uninstall steganography**
Uninstalling steganography-0.1.1:
  /Library/Frameworks/Python.framework/Versions/2.7/bin/steganography
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/steganography-0.1.1-py2.7.egg-info
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/steganography/__init__.py
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/steganography/__init__.pyc
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/steganography/steganography.py
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/steganography/steganography.pyc

하면 찾을수 있습니다.

**Comment by githubrat** [comment]
해결된 문제 닫으면 되지 않을까염 ㅎ
