### ISSUE TITLE
코드 진행 방향

### ISSUE THREAD

**Issue by merrym4n** [GSSecurity/OSS#10]
태수형이 커밋하기 전에는 ICO 파일을 지원하였는데, 커밋을 한 후에는 ICO 확장자에서는 터져버립니다.

![2017-11-30 9 53 00](https://user-images.githubusercontent.com/30262277/33431801-0fbe20ca-d619-11e7-8c1d-40329cef9342.png)

**Comment by merrym4n** [comment]
ICO 확장자의 사용 빈도 등을 기준으로 해서, 이 확장자를 미지원하는 것으로 할지 아니면 이 기능을 포기할지 이야기 해보는 것이 좋을 것 같습니다.

**Comment by merrym4n** [comment]
저는 ICO 지원 보다는 기능이 더 좋을 거 같습니다.

**Comment by githubrat** [comment]
"저는 ICO 지원 보다는 기능이 더 좋을 거 같습니다." 이게 무슨 말이에요?

**Comment by wizleysw** [comment]
일단은 문자로 바꾸게 되면 안터질 것 같으니 문자로 코드 수정 ㄲ

**Comment by wizleysw** [comment]
@류민수 ICO보다는 Checksum 기능이 더  좋을 것 같다고 하네요.

**Comment by 34t3rnull** [comment]
체크섬이 인코딩 중복체크 같은데 일부러 다중 인코딩하는 경우는 없을까요??

**Comment by 34t3rnull** [comment]
일부러하는 경우도 있을 것 같은데 checksum을 다른 방식으로 하는게 좋을 것 같아요

**Comment by merrym4n** [comment]
@34t3rnull 기본적으로 다중 인코딩 안되지 않을까요?
나중에 한것이 덮어쓰는지 확인해보겠습니다.

**Comment by ltshub** [comment]
디코딩기능에 text는 추출해서 보여주는데 디코딩한파일은 안주잖아

**Comment by merrym4n** [comment]
다중 인코딩을 하는 경우가 있을까요? 다중 인코딩이 안되는게 좋지 않을까요?

**Comment by wizleysw** [comment]
다중 인코딩은 허용하면 아니되오

**Comment by merrym4n** [comment]
@merryman - ICO 확장자 지원 안하고 체크섬을 유지
@pwnwiz - checksum value 를 문자로 변경, 다중 인코딩 X
@34t3rnull - 다중 인코딩을 허용, checksum은 다른 방식으로 구현 
@ltshub - 다중 인코딩 X

정리했는데 맞나요?

**Comment by wizleysw** [comment]
아니면 이미 인크립트되었을때 다시 또 하려고하면 경고문 출력하고 인풋받는방법이잇긴한데 그러기 위해서는 두 번 인크립트시 메시지 내용이 변경되는 부분을 해결해야하기에 고민 해볼 문제임

**Comment by 34t3rnull** [comment]
확정이면 mergy해도 되나요???

**Comment by devilzCough** [comment]
처음 체크섬 구현한 분 이전에 구현한 코드 정상작동했나요?

**Comment by ltshub** [comment]
처음에 테스트 할때는 됐는데 지금까지 merge된 코드에 체크썸을 텍스트 앞에 붙이던가 문자로 하던가 그래도 안되면 주석으로 바꿔놓은 부분 깔끔하게 지우도록 할께요

**Comment by devilzCough** [comment]
제가 시크릿 코드를 텍스트 뒤에 붙이고 체크섬을 앞에 붙여봤는데 (시크릿 코드는 뒤에 붙여도 문제가 없는데) 체크섬을 앞에 붙이는 중에 decode 함수에서 에러가 발생합니다

제 브랜치 아마.. devilzChecksum? 인가 여기에 구현해봤는데 (현재 주석처리 했지만) 에러 확인 부탁드려요
@ltshub

**Comment by githubrat** [comment]
이 이슈 해결됐나요?

**Comment by devilzCough** [comment]
@githubrat 아직 안된 듯 하네요. 해결하실 수 있는 분 수정부탁합니다.

**Comment by devilzCough** [comment]
main() 함수
<img width="447" alt="2017-12-05 8 25 03" src="https://user-images.githubusercontent.com/28432479/33604796-9a856f76-d9fa-11e7-9362-f6c115eb20b4.png">

hide_text ()함수
<img width="398" alt="2017-12-05 8 26 09" src="https://user-images.githubusercontent.com/28432479/33604797-9ac46690-d9fa-11e7-9b7b-582baaec220b.png">

@ltshub 가 넣은 체크섬 부분인 것 같은데,
만약 1, 1 픽셀의 값이 is_modify_pixel() 의 조건에 맞는다면 수정될 수 있지 않나요?
적은 확률일 수 있지만 만약 저 픽셀에 텍스트가 삽입되고 r 값을 임의로 33 으로 바꾼다면 decode 시에 문제가 발생할 수 있을 것 같습니다.

저런 방식으로 만들고자 한다면. 제 생각에는
차라리 0, 0 픽셀의 값을 고정하고, 아예 텍스트 삽입시 0, 0 픽셀 이후 부터 하는 것이 좋은 것 같습니다.

제 의견이 맞는지 확실하지 않으니 다른 분 의견 부탁합니다

**Comment by ltshub** [comment]
그렇게 하는것이 좋을것 같네요

**Comment by devilzCough** [comment]
넵 수정해서 풀리퀘했습니다. 아직 코드 테스트를 못해봐서 코드 확인 후 문제 있으면 코멘트 혹은 수정부탁합니다
