### ISSUE TITLE
master 브랜치로 push했습니다.

### ISSUE THREAD

**Issue by 34t3rnull** [GSSecurity/OSS#11]
죄송합니다.. 어떻게 해결해야하나요?

일단 추가한 부분은

```python
import os
.
.
.
print("Input Image Size : {}".format(os.path.getsize(input_image_path)))
print("Output Image size : {}".format(os.path.getsize(output_image_path)))
```

입니다. 제 브랜치로 작업하던 것을 master로 옮겼다가 push를 master 브랜치로 잘못했습니다.
pull request로 했어야하는데 push를 했네요.. 일단 찾아보곤 있는데 여러분들의 의견 부탁드립니다.

**Comment by merrym4n** [comment]
확인해 봤을때 아직은 다 정상적으로 나오는 것 같습니다.
앞으로는 조금 조심해 주시면 감사하겠습니다. ㅎㅎ
