### ISSUE TITLE
인코딩 후 파일 크기

### ISSUE THREAD

**Issue by merrym4n** [GSSecurity/OSS#12]
![image](https://user-images.githubusercontent.com/30262277/33518417-0d931380-d7d8-11e7-95cf-a0df1c01207e.png)
인코딩 후 파일 크기가 줄어 드는데 정상인가요?

**Comment by merrym4n** [comment]
![image](https://user-images.githubusercontent.com/30262277/33518442-54edbbcc-d7d8-11e7-9892-86e6e6eafe45.png)
어떤 경우에는 또 증가하네요

**Comment by 34t3rnull** [comment]
인코딩이 잘 되면 괜찮을 듯 합니다

**Comment by merrym4n** [comment]
공간이 충분하지 않는 경우에는 공간 확보를 위하여 파일의 크기가 증가하는 것 같습니다.
