### ISSUE TITLE
Deal with conflicting files

### ISSUE THREAD

**Issue by merrym4n** [GSSecurity/OSS#16]
파일들이 충돌이 나서 조정을 했는데 맞게했는지 확인 부탁드립니다.

**Comment by githubrat** [comment]
[공지] "고장난 마스터브랜치를 고치자" 각자 쓰고 있던 브랜치는 더이상 마스터브랜치에 머지하기 어려우니 "고장난 마스터브랜치를 고치자" 브랜치에서 새로 브랜치 떠서 작업 부탁드려요.
기존 작업을 이어서 하실분은 깃헙의 특정파일 diff 하는 기능을 이용해 수동으로 작업물 마이그레이션 부탁드릴게요.
