### ISSUE TITLE
WIKI Analyze

### ISSUE THREAD

**Issue by wizleysw** [GSSecurity/OSS#18]
주석 다는 과정을 진행중인데 수정이 많이많이 필요합니다~~

특히 read_text 부분이랑 is_modify_pixel 부분을 중점으로 부탁드립니다

간단히 설명하자면 기존 원본 코드에 대한 설명입니다.

**Comment by devilzCough** [comment]
devilzCheckSum 에 일부 주석 달았습니다 ㅜㅜ
코드 수정되면 머지하려고 했는데 해결이 안됐네요..

**Comment by githubrat** [comment]
```python
def is_modify_pixel(r, g, b):
    """
    :param r: int
    :param g: int
    :param b: int
    :return: bool           // 255 = 8 * 31 + 7
    """
    return r % DIST == g % DIST == b % DIST == 1   //DIST DEFINE 값 8
```

핵심은 이부분,  (r%DIST) == (g%DIST) == (b%DIST) == 1.
r채널 모듈러 8, g채널 모듈러 8, b채널 모듈러8 한 값이 모두 1이어야 True.

즉, 수정된 픽셀은 모두 8로 나눴을 때 나머지가 1인 특징이있음.

**Comment by githubrat** [comment]
```python
def read_text(path):
    """
    read secret text from image
    :param path: str
    :return: str
    """
    img = Image.open(path)
    counter = 0
    result = []
    for y in range(img.size[1]):
        for x in range(img.size[0]):
            r, g, b = img.getpixel((x, y))
            if is_modify_pixel(r, g, b): // DIST의 값이 8인데 r, g, b % DIST 을 실행하여 값이 같은지 확인 
                result.append(counter) //카운터 값 저장 후 1씩 증가
            counter += 1
            if counter == 16:
                counter = 0
    return to_str(''.join([hex(_)[-1:] for _ in result])) 
```

이미지 width, height 를 구해서 (y,x)  형식으로 픽셀 하나하나를 수정된 픽셀인지 확인.
for 문을 돌면서 카운트값이 0 ~ 15까지 돌음. 16픽셀이 half byte를 표현 (0x0~0xF). 16픽셀중 한놈만 수정된놈.
같은 height의 이미지 한줄을 다 읽으면서 값을 half byte 를 계속 저장함.
한줄을 다 읽으면 result를 strjoin 해서 hexstring 으로 만들고, 그것을 to_str 을 이용해 실제 텍스트로 변환함.
수정된 픽셀이면 result 에 현재 카운터값을 을 저장.

**Comment by githubrat** [comment]
위키 정리는 맡길게요 ㅠㅠ... 지금 넘바빠서 ㅠㅠ

**Comment by merrym4n** [comment]
@pwnwiz 분석 끝났으면 이슈 닫겠습니다.
