### ISSUE TITLE
라이센스

### ISSUE THREAD

**Issue by merrym4n** [GSSecurity/OSS#20]
MIT 라이센스로 하면 좋을 것 같은데 어떤게 좋을까요?

**Comment by 34t3rnull** [comment]
G:GREAT
P:Perfect
L:Legend

GPL 어떤가요? 이름부터 멋지네요 ㅎㅎ

**Comment by wizleysw** [comment]
mit

**Comment by merrym4n** [comment]
다들 의견 주세요 12시 지나면 갱신하겠습니다.
@githubrat @devilzCough @ltshub

**Comment by githubrat** [comment]
MIT 입학하고싶다

**Comment by devilzCough** [comment]
mit  해도 괜찮을듯 싶음

**Comment by merrym4n** [comment]
MIT 라이센스로 하겠습니다.
