### ISSUE TITLE
라이브러리 관련 이슈

### ISSUE THREAD

**Issue by merrym4n** [GSSecurity/OSS#23]
지금까지 수정한 steganography.py 파일을 import 할수 있을까요? (views.py에서)
지금은 추가로 steganograhy 를 설치 해줘야 작동을 하는데, 이것을 수정한 파일로 해서 import 해주실분 있나요?

**Comment by githubrat** [comment]
당연히 임포트 할 수 있죠

**Comment by githubrat** [comment]
인코더를 만든 영수에게 묻습니다. @34t3rnull

**Comment by wizleysw** [comment]
sys.path.append('/Users/pwnwiz/OSS/OSS/lib/steganography')
#sys.path.append('../lib/steganography/steganography')
#import steganography
from steganography import steganography

해보았지만 오류 .. 혹시 방법 아시는분

**Comment by wizleysw** [comment]
해결 완료 ~ pull 할게요
