### ISSUE TITLE
사소한 문의??

### ISSUE THREAD

**Issue by wizleysw** [GSSecurity/OSS#24]
![2017-12-05 8 42 38](https://user-images.githubusercontent.com/32321029/33605395-ea6ca8e0-d9fc-11e7-8f68-860b97ea9415.png)
![2017-12-05 8 42 41](https://user-images.githubusercontent.com/32321029/33605396-eba2755a-d9fc-11e7-8f00-c031da1e06a6.png)

둘다 GET ETCHED FILE 이라는 문구????? @githubrat

**Comment by wizleysw** [comment]
uplad -> upload??

**Comment by githubrat** [comment]
앗 실슈
Extract는 원하는 맛깔나는 문장으로 바꿔주세요 ㅋㅋ

**Comment by wizleysw** [comment]
오타 수정 및 LEAK THE SECRET 으로 변경완료
