### ISSUE TITLE
웹에서 Decode하는 함수는 어디에다가 구현해야할까요??

### ISSUE THREAD

**Issue by 34t3rnull** [GSSecurity/OSS#25]
인코딩은 했는데 디코딩은 함수명을 어떻게 해야할 지 모르겠어요 @githubrat

**Comment by devilzCough** [comment]
기존 코드는 read_text() 로 되어있고, 텍스트를 찾아낸다는 의미로 지어도 될듯하네요

**Comment by githubrat** [comment]
네 read_text로 만들면되지 않나요??

**Comment by 34t3rnull** [comment]
아 read_text로 view.py에 구현해놓겠습니다 ㅎㅎ
