### ISSUE TITLE
스테가노그래피 인코더는 완성된건가요?

### ISSUE THREAD

**Issue by githubrat** [GSSecurity/OSS#26]
키, 메시지 올려서 내려받은 스테가노처리된 이미지를 CLI 환경에서 디코딩해서 이미지 나오는지 보면 좋을것같은뎀 흠

**Comment by merrym4n** [comment]
우선 업로드, 다운로드 구현부터 마무리해야 할거 같습니다.
지금 업로드는 끝난거 맞죠?

**Comment by 34t3rnull** [comment]
넵넵 업로드는 잘 되는 곳 같아요

**Comment by 34t3rnull** [comment]
아 지금 사용한 모듈이 steganography.steganography에다 함수를 바로 뽑아썼거든요.. 제 실력이 부족한지라 githubrat이 말씀하신 기능을 어떻게 구현해야할지 모르겠어요..
