### ISSUE TITLE
key값 대조 관련

### ISSUE THREAD

**Issue by 34t3rnull** [GSSecurity/OSS#29]
web에서 form 받는 것이 msg, key, file 받는데요 이 사용자가 이 이미지의 인코더라는 사실을 어떻게 확인할까요?? 의견이 궁금합니다. 쿼리문 써주시면 ㄳㄳ

**Comment by pwnwiz** [comment]
아주 날카로운 질문이네요.

**Comment by 34t3rnull** [comment]
이미지에 박아서 해결하면 되겠네요 ㄳㄳ
