### ISSUE TITLE
모든 출력 확장자는 PNG로 정해져 있음

### ISSUE THREAD

**Issue by merrym4n** [GSSecurity/OSS#3]
고칠까요? 아니면 유지할까요?

**Comment by githubrat** [comment]
좀 더 시간 두고 생각해보면 좋을 것 같아요 당장은 다들 할일 있으니~

**Comment by wizleysw** [comment]
지원되는걸 좀 더 파악해봅시다

**Comment by merrym4n** [comment]
여러 문서들 및 툴들을 확인해 본 결과 대다수가 PNG로 고정되어 있습니다. 그 이유로는 다른 확장자로 출력을 할 경우 파일이 반복적으로 손상이 될 것입니다. 그 과정에서 스테가노그래피로 숨긴 정보가 손상될 수 있을 가능성이 존재하기 때문에 PNG로 확장자를 고정하여 놓은 것 같습니다.
