### ISSUE TITLE
인자값 변경에 대한 공지

### ISSUE THREAD

**Issue by wizleysw** [GSSecurity/OSS#32]
영수가 인자값 형태로 secretCode를 받으면 좋겠다고 해서 argc를 한개씩 늘렸고, 마지막 부분에 secretCode를
입력받는 방법을 사용하였습니다.

1. steganography -e input.png output.png msg secretCode
수정 1. argc 5 -> 6
수정 2. argv[5]

2. steganography -d output.png secretCode
수정 1. argc 3 -> 4
수정 2. argv[4]

**Comment by merrym4n** [comment]
확인 완료

**Comment by wizleysw** [comment]
확인다 하신걸로 알고 닫습니다
