### ISSUE TITLE
확장자가 없을 시 예외 처리 오류발견(???)

### ISSUE THREAD

**Issue by ltshub** [GSSecurity/OSS#8]
![sadasd](https://user-images.githubusercontent.com/33980077/33416863-1a4283ce-d5e2-11e7-9ddd-80fe4d79c05e.PNG)

**Comment by merrym4n** [comment]
![2017-11-30 9 47 00](https://user-images.githubusercontent.com/30262277/33431535-0813040e-d618-11e7-8018-1a36b79fdeb0.png)
예외 처리 하였습니다.

**Comment by ltshub** [comment]
bb
